# Generated by Django 5.1.5 on 2025-01-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('lose weight', 'Lose Weight'), ('gain weight', 'Gain Weight'), ('maintain weight', 'Maintain Weight'), ('muscle_building', 'Muscle Building')], max_length=20)),
                ('calorie_range_min', models.IntegerField(default=0)),
                ('calorie_range_max', models.IntegerField(default=0)),
                ('breakfast', models.TextField(default='')),
                ('lunch', models.TextField(default='')),
                ('dinner', models.TextField(default='')),
                ('snacks', models.TextField(default='')),
                ('snacks2', models.TextField(default='')),
                ('snacks3', models.TextField(default='')),
                ('protein_percentage', models.IntegerField(default=0)),
                ('carbs_percentage', models.IntegerField(default=0)),
                ('fat_percentage', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Diet Plan',
                'verbose_name_plural': 'Diet Plans',
                'ordering': ['goal', 'calorie_range_min'],
            },
        ),
    ]
