# Generated by Django 5.1.5 on 2025-02-03 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietplan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelectedDietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories', models.IntegerField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('selected_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietplan.dietplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selected_diet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Selected Diet Plan',
                'verbose_name_plural': 'User Selected Diet Plans',
            },
        ),
    ]
