# Generated by Django 5.1.5 on 2025-02-12 13:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('muscle gain', 'Muscle Gain'), ('fat loss', 'Fat Loss'), ('fitness', 'Fitness')], max_length=30)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=30)),
                ('sessions_per_week', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('rest_between_sets', models.IntegerField(help_text='Rest time in seconds', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(180)])),
                ('day1_title', models.CharField(max_length=60)),
                ('day1_exercises', models.TextField()),
                ('day2_title', models.CharField(max_length=60)),
                ('day2_exercises', models.TextField()),
                ('day3_title', models.CharField(max_length=60)),
                ('day3_exercises', models.TextField()),
                ('day4_title', models.CharField(blank=True, max_length=60, null=True)),
                ('day4_exercises', models.TextField(blank=True, null=True)),
                ('day5_title', models.CharField(blank=True, max_length=60, null=True)),
                ('day5_exercises', models.TextField(blank=True, null=True)),
                ('day6_title', models.CharField(blank=True, max_length=60, null=True)),
                ('day6_exercises', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSelectedWorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selected_workout_plan', to=settings.AUTH_USER_MODEL)),
                ('selected_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_selections', to='workoutplan.workoutplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
