# Generated by Django 5.1.5 on 2025-02-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='day3_exercises',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='day3_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
