# Generated by Django 5.1.5 on 2025-01-30 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_activity_level_alter_profile_diet_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activity_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='diet_goal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='plan_goal',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DietPlanInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_level', models.CharField(choices=[('very active', 'Very Active'), ('active', 'Active'), ('moderately active', 'Moderately Active'), ('lightly active', 'Lightly Active')], max_length=20)),
                ('diet_goal', models.CharField(choices=[('lose weight', 'Lose Weight'), ('gain weight', 'Gain Weight'), ('maintain weight', 'Maintain Weight'), ('muscle_building', 'Muscle Building')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diet_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='data_diet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='accounts.dietplaninfo'),
        ),
        migrations.CreateModel(
            name='WorkoutPlanInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20)),
                ('plan_goal', models.CharField(choices=[('muscle gain', 'Muscle Gain'), ('fat loss', 'Fat Loss'), ('fitness', 'Fitness')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='data_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='accounts.workoutplaninfo'),
        ),
    ]
